
// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package zz

import (
    "fmt"
    "zombiezen.com/go/sqlite"

    
    "time"
    "github.com/delaneyj/toolbelt"
    
)


type GetLocationsRes struct {
        Id int64 `json:"id"`
        Lat float64 `json:"lat"`
        Long float64 `json:"long"`
        CreatedAt time.Time `json:"created_at"`
}




type GetLocationsStmt struct {
    stmt *sqlite.Stmt
}

func GetLocations(tx *sqlite.Conn) *GetLocationsStmt {
    // Prepare the statement into connection cache
    stmt := tx.Prep(`
SELECT
    id, lat, long, created_at
FROM
    locations
ORDER BY
    created_at
    `)
    ps := &GetLocationsStmt{stmt: stmt}
    return ps
}

func (ps *GetLocationsStmt) Run(
    ) (
            res []GetLocationsRes,
    err error,
) {
    defer ps.stmt.Reset()


    // Execute the query
        for {
            if hasRow, err := ps.stmt.Step(); err != nil {
                return res, fmt.Errorf("failed to execute {{.Name.Lower}} SQL: %w", err)
            } else if !hasRow {
                break
            }

                row := GetLocationsRes{}
            row.Id =         ps.stmt.ColumnInt64(0)
            row.Lat =         ps.stmt.ColumnFloat(1)
            row.Long =         ps.stmt.ColumnFloat(2)
            row.CreatedAt =         toolbelt.JulianDayToTime(ps.stmt.ColumnFloat(3))
            res = append(res, row)
        }

    return res, nil
}

func OnceGetLocations(
    tx *sqlite.Conn,
    ) (
            res []GetLocationsRes,
    err error,
) {
    ps := GetLocations(tx)

    return ps.Run(

    )
}

